import type { Issue } from '@/lib/types';
import { PlaceHolderImages } from '@/lib/placeholder-images';

const findImage = (id: string) => PlaceHolderImages.find(img => img.id === id) || { imageUrl: '', imageHint: '' };

export const issues: Issue[] = [
  {
    id: 'IS-1',
    title: 'Major Pothole on Main St',
    description: 'A large and dangerous pothole has formed in the right lane of Main Street, just past the intersection with Oak Avenue. It has already caused a flat tire for one driver.',
    category: 'Pothole',
    status: 'In Progress',
    address: '123 Main St, Springfield',
    department: 'Department of Road Construction',
    location: { lat: 34.0522, lng: -118.2437 },
    imageUrl: findImage('issue-pothole').imageUrl,
    imageHint: findImage('issue-pothole').imageHint,
    reportedAt: '2024-07-20T10:00:00Z',
    updatedAt: '2024-07-21T14:30:00Z',
    reporter: { name: 'Alice Johnson', avatarUrl: 'https://i.pravatar.cc/150?u=alice' },
  },
  {
    id: 'IS-2',
    title: 'Streetlight out at Elm & 2nd',
    description: 'The streetlight at the corner of Elm Street and 2nd Avenue has been out for three nights. It\'s a busy intersection and feels unsafe after dark.',
    category: 'Broken Streetlight',
    status: 'Reported',
    address: '456 Elm St, Springfield',
    department: 'Department of Urban Development & Housing',
    location: { lat: 34.055, lng: -118.245 },
    imageUrl: findImage('issue-streetlight').imageUrl,
    imageHint: findImage('issue-streetlight').imageHint,
    reportedAt: '2024-07-21T21:15:00Z',
    updatedAt: '2024-07-21T21:15:00Z',
    reporter: { name: 'Bob Williams', avatarUrl: 'https://i.pravatar.cc/150?u=bob' },
  },
  {
    id: 'IS-3',
    title: 'Graffiti on Park Wall',
    description: 'Large amount of graffiti spray-painted on the community park wall facing the playground.',
    category: 'Graffiti',
    status: 'Resolved',
    address: '789 Park Ave, Springfield',
    department: 'Department of Urban Development & Housing',
    location: { lat: 34.05, lng: -118.24 },
    imageUrl: findImage('issue-graffiti').imageUrl,
    imageHint: findImage('issue-graffiti').imageHint,
    reportedAt: '2024-07-18T08:30:00Z',
    updatedAt: '2024-07-20T17:00:00Z',
    reporter: { name: 'Charlie Brown', avatarUrl: 'https://i.pravatar.cc/150?u=charlie' },
  },
  {
    id: 'IS-4',
    title: 'Trash cans overflowing at bus stop',
    description: 'The trash and recycling bins at the bus stop on 5th Avenue are completely full and overflowing onto the sidewalk. It\'s been like this for days.',
    category: 'Trash Overflow',
    status: 'Reported',
    address: '101 5th Ave, Springfield',
    department: 'Department of Urban Development & Housing',
    location: { lat: 34.048, lng: -118.25 },
    imageUrl: findImage('issue-trash').imageUrl,
    imageHint: findImage('issue-trash').imageHint,
    reportedAt: '2024-07-22T11:00:00Z',
    updatedAt: '2024-07-22T11:00:00Z',
    reporter: { name: 'Diana Prince', avatarUrl: 'https://i.pravatar.cc/150?u=diana' },
  },
];
