import type { Department } from './types';

export const departments: Department[] = [
  { name: 'Department of Agriculture, Animal Husbandry & Co-operative' },
  { name: 'Department of Building Construction' },
  { name: 'Department of Cabinet Election' },
  { name: 'Department of Cabinet Secretariat and Vigilance' },
  { name: 'Department of Commercial Taxes' },
  { name: 'Department of Drinking Water and Sanitation' },
  { name: 'Department of Energy' },
  { name: 'Department of Excise and Prohibition' },
  { name: 'Department of Finance' },
  { name: 'Department of Food, Public Distribution & Consumer Affairs' },
  { name: 'Department of Forest, Environment & Climate Change' },
  { name: 'Department of Health, Medical Education & Family Welfare' },
  { name: 'Department of Higher and Technical Education' },
  { name: 'Department of Home, Jail & Disaster Management' },
  { name: 'Department of Industries' },
  { name: 'Department of Information & Public Relations' },
  { name: 'Department of Information Technology & e-Governance' },
  { name: 'Department of Labour, Employment, Training and Skill Development' },
  { name: 'Department of Law' },
  { name: 'Department of Mines & Geology' },
  { name 'Department of Panchayati Raj' },
  { name: 'Department of Personnel, Administrative Reforms & Rajbhasha' },
  { name: 'Department of Planning & Development' },
  { name: 'Department of Revenue, Registration & Land Reforms' },
  { name: 'Department of Road Construction' },
  { name: 'Department of Rural Development' },
  { name: 'Department of Rural Works' },
  { name: 'Department of Scheduled Tribe, Scheduled Caste, Minority and Backward Class Welfare' },
  { name: 'Department of School Education & Literacy' },
  { name: 'Department of Tourism, Arts, Culture, Sports & Youth Affairs' },
  { name: 'Department of Transport' },
  { name: 'Department of Urban Development & Housing' },
  { name: 'Department of Water Resources' },
  { name: 'Department of Women, Child Development & Social Security' },
];
